# Transaction rules

LARGE_TRANSACTION_THRESHOLD=100000
LARGE_TRANSACTION_SCORE=30

#Account frequency rules

HIGH_FREQUENCY_THRESHOLD=5
HIGH_FREQUENCY_SCORE=20

#Velocity rules

VELOCITY_WINDOW_MINUTES=30
HIGH_VELOCITY_THRESHOLD=3
HIGH_VELOCITY_SCORE=30

#Risk country rules

HIGH_RISK_COUNTRIES={"XX","YY"}
HIGH_RISK_COUNTRY_SCORE=30

#Network rules

CYCLE_WINDOW_MINUTES=30
CYCLE_AMOUNT_THRESHOLD=100000
CYCLE_RISK_SCORE=40

#final risk levels

CRITICAL_THRESHOLD=80
HIGH_THRESHOLD=60
MEDIUM_THRESHOLD=30